### ISSUE TITLE
Original source

### ISSUE THREAD

**Issue by tobiasBora** [christian-nils/phd_presentation#1]
I really like your presentation, with all these nice GSAP animations. By any chance do you have a link to the original source so that I can see how you design them and integrated the auto play videos inside Eagler together with the menu? (this template https://github.com/christian-nils/presentation_template does not contains GSAP, videos...)

**Comment by christian-nils** [comment]
Would it be https://github.com/christian-nils/phd_defense_src ? I am not sure it is super well organized/coded though :)
I am using [sli.dev](https://github.com/slidevjs/slidev) now for my slideshows.

**Comment by tobiasBora** [comment]
Cool, thanks a lot! Who, you coded all the gsap manually? Looks like a lot of work ^^ Concerning sli.dev, it looks awesome, sadly it is not enough hackable to provide more advanced features :'-( https://github.com/slidevjs/slidev/issues/465 https://github.com/slidevjs/slidev/issues/464

**Comment by christian-nils** [comment]
Ahah, yeah. It took some time but that was great to practice GSAP. 
For your issues with sli.dev, did you consider using _v-click_ to simulate multiple pages or even to control your video?

**Comment by tobiasBora** [comment]
Ahah you did a great job. The problem of `v-click` is that it won't generate a new page number…

**Comment by christian-nils** [comment]
Ok, I see. You would use the page number for what?

**Comment by tobiasBora** [comment]
Simply to display the page number (in the lower right and/or via a colored line) to keep track of the progress ;-)

**Comment by christian-nils** [comment]
Maybe using the page number and the click number would be sufficient? Like {{page}}-{{click}}
Similarly, you could make a progress bar that you divide by the number of page. And each page block on the bar would be divided by the number of clicks for that page.

**Comment by tobiasBora** [comment]
I could certainly do something like that yes... but the semantic is a bit broken, and the page number will look weird. Same for the progress bar: if I have, say, just two slides, with the first one being a long video with many cuts and the second is just "thanks", then people will think that during all the presentation I'm very far from the end. I may try to count the number of clicks as normal slides, but then I have other problems... Also, I will lose the ability to have an overview on my slides, and similarly, I may also have troubles when defining table of contents if all of them are on the same slide... I guess I prefer to design myself/find a more generic tool directly than trying to fight against a tool not designed for my needs.

Anyway, thanks you so much for your help, it was very helpful ;-)
